# This file specifies the parameters of the Cooperative Co-Evolutionary Algorithm with Projection-based Self-Tuning Feature Grouping (CCPSTFG)

[coevolution]
subpop_sizes = [30]
max_gen = 10000
max_gen_without_improvement = 100

[decomposition]
method = "clustering"
drop = true
clustering_model_type = "agglomerative_clustering"

[collaboration]
method = "best"

[wrapper]
task = "classification"
model_type = "k_nearest_neighbors"

[evaluation]
fitness_function = "penalty"
eval_function = "accuracy"
eval_mode = "k_fold"
weights = [1.00, 0.00]

[optimizer]
method = "GA"
selection_method = "generational"
mutation_rate = 0.05
crossover_rate = 1.00
tournament_sample_size = 1
elite_size = 1